# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - launcher: null
  - platform: gpu
  - paths: default
  - hydra: default
  - _self_
task_name: generate_md
pdb_dir: ${paths.data_dir}/pdbs
output_dir: ${paths.data_dir}/md/${pdb_filename}_${temperature}_${num_frames}
pdb_filename: null
temperature: 310
warmup_steps: 50_000
frame_interval: 10_000 # How many integration steps between frames collected
num_frames: 10_000 # Total number of frames to generate
save_interval: 10 # How many frames per saved npz file, shape = (save_interval, N, 3)
log_freq: 10
output_filename: trajectories
