# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - launcher: null
  - platform: gpu
  - paths: default
  - hydra: default
  - _self_
task_name: md
pdb_dir: ${paths.data_dir}/pdbs
output_dir: ${paths.data_dir}/md/${pdb_filename}_${temperature}_${num_steps}
pdb_filename: null
temperature: 310
warmup_steps: 50_000
step_size: 10_000
num_steps: 10_000
log_freq: 100
ckpt_freq: 1000
