# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - paths: default
  - _self_ 
task_name: seq_to_pdb
seq_filename: null
hydra:
  run:
    dir: ${paths.output_dir}/seq_to_pdb