# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 4
    mem_gb: 24
    gres: gpu:1
    timeout_min: 7000
    array_parallelism: 1000 # max num of tasks to run in parallel (via job array)
    exclude: cn-b[001-005],cn-e[002-003],cn-g[001-029],cn-k[001-004]
    setup:
      - "micromamba activate ${oc.env:MICROMAMBA_ENV}"
