# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

# hydra:
#   launcher:
#     partition: long
#     cpus_per_task: 8
#     mem_gb: 64
#     gres: gpu:2
#     timeout_min: 2880
#     exclude: cn-g[005-012,014,017-026] # exclude mig for ddp
#     array_parallelism: 10 # max num of tasks to run in parallel (via job array)
#     setup:
#       - "micromamba activate ${oc.env:MICROMAMBA_ENV}"

hydra:
  launcher:
    partition: short-unkillable
    cpus_per_task: 6
    mem_gb: 128
    gres: gpu:h100:4
    timeout_min: 180
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "micromamba activate ${oc.env:MICROMAMBA_ENV}"
