# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 1
    mem_gb: 8
    gres: gpu:l40s:1
    timeout_min: 2880
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "micromamba activate ${oc.env:MICROMAMBA_ENV}"
