# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 3
    mem_gb: 24
    gres: gpu:rtx8000:1
    timeout_min: 2880
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "micromamba activate ${oc.env:MICROMAMBA_ENV}"
